  // --- BESTIARY MONSTER CARDS DATABASE ---
  export const MONSTER_CARDS_DATA = Object.assign(window.MONSTER_CARDS_DATA || {}, {
    slime: {
      name: "Green Slime",
      set: "Whispering Woods",
      hint: "Floors 1-12",
      stat: "maxHpPctBonus",
      statName: "Max HP %",
      statLabel: "Max HP %",
      statKey: "maxHpPctBonus",
      bonusStat: "maxHpPctBonus",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    sprout: {
      name: "Eldritch Sprout",
      set: "Whispering Woods",
      hint: "Floors 1-12",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    thorn_wyrm: {
      name: "Thorn Wyrm",
      set: "Whispering Woods",
      hint: "Floors 1-12",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    arachnid_treant: {
      name: "Arachnid Treant",
      set: "Guardian Wardens",
      hint: "Floor 12 Boss",
      stat: "critChance",
      statName: "Crit Chance",
      statLabel: "Crit Chance",
      statKey: "critChance",
      bonusStat: "critChance",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    golem: {
      name: "Stone Golem",
      set: "Mountain Peaks",
      hint: "Floors 13-24",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.008,
      baseVal: 0.008,
      perRank: 0.008,
      bonusVal: 0.008,
      isPct: true,
    },
    wyrmling: {
      name: "Frost Wyrmling",
      set: "Mountain Peaks",
      hint: "Floors 13-24",
      stat: "maxHpPctBonus",
      statName: "Max HP %",
      statLabel: "Max HP %",
      statKey: "maxHpPctBonus",
      bonusStat: "maxHpPctBonus",
      val: 0.012,
      baseVal: 0.012,
      perRank: 0.012,
      bonusVal: 0.012,
      isPct: true,
    },
    gargoyle: {
      name: "Gargoyle Warden",
      set: "Mountain Peaks",
      hint: "Floors 13-24",
      stat: "block",
      statName: "Block Rate",
      statLabel: "Block Rate",
      statKey: "block",
      bonusStat: "block",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    rust_nibbler: {
      name: "Rust Nibbler",
      set: "Mountain Peaks",
      hint: "Floors 13-24",
      stat: "qly",
      statName: "Drop Quality",
      statLabel: "Drop Quality",
      statKey: "qly",
      bonusStat: "qly",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    gilded_scuttler: {
      name: "Gilded Scuttler",
      set: "Mountain Peaks",
      hint: "Sector 1 rare",
      stat: "gold",
      statName: "Gold Multi",
      statLabel: "Gold Multi",
      statKey: "gold",
      bonusStat: "gold",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    mimic_shield: {
      name: "Mimic Shield",
      set: "Mountain Peaks",
      hint: "Sectors 1 & 6",
      stat: "parry",
      statName: "Parry Rate",
      statLabel: "Parry Rate",
      statKey: "parry",
      bonusStat: "parry",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    aegis_goliath: {
      name: "Aegis Goliath",
      set: "Guardian Wardens",
      hint: "Floor 24 Boss",
      stat: "block",
      statName: "Block Rate",
      statLabel: "Block Rate",
      statKey: "block",
      bonusStat: "block",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    magma_elemental: {
      name: "Magma Elemental",
      set: "Inferno Depths",
      hint: "Floors 25-36",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.008,
      baseVal: 0.008,
      perRank: 0.008,
      bonusVal: 0.008,
      isPct: true,
    },
    lava_serpent: {
      name: "Lava Serpent",
      set: "Inferno Depths",
      hint: "Floors 25-36",
      stat: "critDamage",
      statName: "Crit Multi",
      statLabel: "Crit Multi",
      statKey: "critDamage",
      bonusStat: "critDamage",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    hell_bat: {
      name: "Hell Bat",
      set: "Inferno Depths",
      hint: "Floors 25-36",
      stat: "moveSpeed",
      statName: "Move Speed",
      statLabel: "Move Speed",
      statKey: "moveSpeed",
      bonusStat: "moveSpeed",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    slag_slime: {
      name: "Slag Slime",
      set: "Inferno Depths",
      hint: "Floors 25-36",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    overlord_iron_vault: {
      name: "Overlord Iron Vault",
      set: "Guardian Wardens",
      hint: "Floor 36 Boss",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    swamp_basilisk: {
      name: "Swamp Basilisk",
      set: "Fungal Swamp",
      hint: "Floors 37-48",
      stat: "maxHpPctBonus",
      statName: "Max HP %",
      statLabel: "Max HP %",
      statKey: "maxHpPctBonus",
      bonusStat: "maxHpPctBonus",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    toxic_fly: {
      name: "Toxic Fly",
      set: "Fungal Swamp",
      hint: "Floors 37-48",
      stat: "moveSpeed",
      statName: "Move Speed",
      statLabel: "Move Speed",
      statKey: "moveSpeed",
      bonusStat: "moveSpeed",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    marsh_ghost: {
      name: "Marsh Ghost",
      set: "Fungal Swamp",
      hint: "Floors 37-48",
      stat: "parry",
      statName: "Parry Rate",
      statLabel: "Parry Rate",
      statKey: "parry",
      bonusStat: "parry",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    corroded_golem: {
      name: "Corroded Golem",
      set: "Fungal Swamp",
      hint: "Floors 37-48",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.012,
      baseVal: 0.012,
      perRank: 0.012,
      bonusVal: 0.012,
      isPct: true,
    },
    corrosive_abomination: {
      name: "Corrosive Abomination",
      set: "Guardian Wardens",
      hint: "Floor 48 Boss",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    void_orb: {
      name: "Void Orb",
      set: "Void Singularity",
      hint: "Floors 49-60",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.012,
      baseVal: 0.012,
      perRank: 0.012,
      bonusVal: 0.012,
      isPct: true,
    },
    void_crawler: {
      name: "Void Crawler",
      set: "Void Singularity",
      hint: "Floors 49-60",
      stat: "critChance",
      statName: "Crit Chance",
      statLabel: "Crit Chance",
      statKey: "critChance",
      bonusStat: "critChance",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    void_spectre: {
      name: "Void Spectre",
      set: "Void Singularity",
      hint: "Floors 49-60",
      stat: "parry",
      statName: "Parry Rate",
      statLabel: "Parry Rate",
      statKey: "parry",
      bonusStat: "parry",
      val: 0.005,
      baseVal: 0.005,
      perRank: 0.005,
      bonusVal: 0.005,
      isPct: true,
    },
    void_wraith: {
      name: "Void Wraith",
      set: "Void Singularity",
      hint: "Sector 4 rare",
      stat: "critDamage",
      statName: "Crit Multi",
      statLabel: "Crit Multi",
      statKey: "critDamage",
      bonusStat: "critDamage",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    rift_drifter: {
      name: "Rift Drifter",
      set: "Void Singularity",
      hint: "Sector 4 rare",
      stat: "drop",
      statName: "Drop Rate",
      statLabel: "Drop Rate",
      statKey: "drop",
      bonusStat: "drop",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    void_overseer: {
      name: "Void Overseer",
      set: "Cosmic Overlords",
      hint: "Floor 60 Boss",
      stat: "maxHpPctBonus",
      statName: "Max HP %",
      statLabel: "Max HP %",
      statKey: "maxHpPctBonus",
      bonusStat: "maxHpPctBonus",
      val: 0.02,
      baseVal: 0.02,
      perRank: 0.02,
      bonusVal: 0.02,
      isPct: true,
    },
    clockwork_scarab: {
      name: "Clockwork Scarab",
      set: "Temporal Sanctorum",
      hint: "Floors 61+",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    temporal_watcher: {
      name: "Temporal Watcher",
      set: "Temporal Sanctorum",
      hint: "Sector 5 rare",
      stat: "gold",
      statName: "Gold Multi",
      statLabel: "Gold Multi",
      statKey: "gold",
      bonusStat: "gold",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    clockwork_drone: {
      name: "Clockwork Drone",
      set: "Temporal Sanctorum",
      hint: "Floors 61+",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    star_weaver: {
      name: "Star Weaver",
      set: "Temporal Sanctorum",
      hint: "Floors 61+",
      stat: "critChance",
      statName: "Crit Chance",
      statLabel: "Crit Chance",
      statKey: "critChance",
      bonusStat: "critChance",
      val: 0.008,
      baseVal: 0.008,
      perRank: 0.008,
      bonusVal: 0.008,
      isPct: true,
    },
    coin_elemental: {
      name: "Coin Elemental",
      set: "Temporal Sanctorum",
      hint: "Sector 5 rare",
      stat: "gold",
      statName: "Gold Multi",
      statLabel: "Gold Multi",
      statKey: "gold",
      bonusStat: "gold",
      val: 0.02,
      baseVal: 0.02,
      perRank: 0.02,
      bonusVal: 0.02,
      isPct: true,
    },
    cyber_wraith: {
      name: "Cyber Wraith",
      set: "Cyberspace Nexus",
      hint: "Floors 73+",
      stat: "drop",
      statName: "Drop Rate",
      statLabel: "Drop Rate",
      statKey: "drop",
      bonusStat: "drop",
      val: 0.015,
      baseVal: 0.015,
      perRank: 0.015,
      bonusVal: 0.015,
      isPct: true,
    },
    neon_spider: {
      name: "Neon Spider",
      set: "Cyberspace Nexus",
      hint: "Floors 61+",
      stat: "moveSpeed",
      statName: "Move Speed",
      statLabel: "Move Speed",
      statKey: "moveSpeed",
      bonusStat: "moveSpeed",
      val: 0.02,
      baseVal: 0.02,
      perRank: 0.02,
      bonusVal: 0.02,
      isPct: true,
    },
    wireframe_orb: {
      name: "Wireframe Orb",
      set: "Cyberspace Nexus",
      hint: "Floors 61+",
      stat: "qly",
      statName: "Drop Quality",
      statLabel: "Drop Quality",
      statKey: "qly",
      bonusStat: "qly",
      val: 0.01,
      baseVal: 0.01,
      perRank: 0.01,
      bonusVal: 0.01,
      isPct: true,
    },
    cursed_blade: {
      name: "Cursed Blade",
      set: "Cyberspace Nexus",
      hint: "Floors 61+",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.02,
      baseVal: 0.02,
      perRank: 0.02,
      bonusVal: 0.02,
      isPct: true,
    },
    animated_armor: {
      name: "Animated Armor",
      set: "Cyberspace Nexus",
      hint: "Floors 61+",
      stat: "defPctBonus",
      statName: "Defense %",
      statLabel: "Defense %",
      statKey: "defPctBonus",
      bonusStat: "defPctBonus",
      val: 0.018,
      baseVal: 0.018,
      perRank: 0.018,
      bonusVal: 0.018,
      isPct: true,
    },
    hoard_mimic: {
      name: "Hoard Mimic",
      set: "Cosmic Overlords",
      hint: "Triggered from Chests",
      stat: "drop",
      statName: "Drop Rate",
      statLabel: "Drop Rate",
      statKey: "drop",
      bonusStat: "drop",
      val: 0.02,
      baseVal: 0.02,
      perRank: 0.02,
      bonusVal: 0.02,
      isPct: true,
    },
    chronos_arbitrator: {
      name: "Chronos Arbitrator",
      set: "Cosmic Overlords",
      hint: "Floor 72 Boss",
      stat: "critDamage",
      statName: "Crit Multi",
      statLabel: "Crit Multi",
      statKey: "critDamage",
      bonusStat: "critDamage",
      val: 0.02,
      baseVal: 0.02,
      perRank: 0.02,
      bonusVal: 0.02,
      isPct: true,
    },
    nexus_overseer: {
      name: "Nexus Overseer",
      set: "Cosmic Overlords",
      hint: "Floor 84 Boss",
      stat: "atkPctBonus",
      statName: "Attack %",
      statLabel: "Attack %",
      statKey: "atkPctBonus",
      bonusStat: "atkPctBonus",
      val: 0.025,
      baseVal: 0.025,
      perRank: 0.025,
      bonusVal: 0.025,
      isPct: true,
    },
  });
